### ISSUE TITLE
 You must use the en.json file due to your Source Locale setting

### ISSUE THREAD

**Issue by iospoisson** [codegrue/auto-translate-json#34]
I dont know what i am doing wrong

"AutoTranslateJSON: You must use the en.json file due to your Source Locale setting."

**Comment by iospoisson** [comment]
Sorted ,i rename the working folder to "translations" et voila it is working :)

**Comment by topce** [comment]
Not sure what was problem.
@codegrue  if you have time maybe to deploy extension 
there is support for DeepL and also some small bug fixes

**Comment by codegrue** [comment]
I get this error trying to build: 

X [ERROR] Could not resolve "form-data"

    src/deepl.ts:1:26:
      1 │ import FormData = require('form-data');
        ╵                           ~~~~~~~~~~~

  You can mark the path "form-data" as external to exclude it from the bundle, which will remove
  this error. You can also surround this "require" call with a try/catch block to handle this
  failure at run-time instead of bundle-time.

**Comment by topce** [comment]
@codegrue 
Thank you for feedback
Did you try npm install
I see it in dependencies in package.json on line 154
"form-data": "^4.0.0",

**Comment by topce** [comment]
@codegrue **thank you for help!**
not related to this one
I also thought that we can refactor project to 
create one separate npm library 
and put code there and from extension just
call this library.
Basically to decouple it from vs code extension.
So npm  library  could be used  used independently like from command line,
CI/CD
or included in some other projects .
**What do you think?**

**Comment by codegrue** [comment]
I like that idea. Was I supposed to make you a co-author?

**Comment by topce** [comment]
> I like that idea. Was I supposed to make you a co-author?
@codegrue  no need you can do it your self if you want ,
of course I can help if you need me.
We can do it on your github/npm account.
Idea is to have one new project put backend code there and keep UI (vs code) in this repo
Build backend  and publish in npm 
then just reference backend npm libarary in package.json.

**Comment by codegrue** [comment]
Published 1.1.4

**Comment by topce** [comment]
Hello @codegrue 
I decoupled your project on 2 
https://github.com/topce/auto-translate-json-library (npm library) invite you as contributor 
https://www.npmjs.com/package/auto-translate-json-library
and on fork of your project create branch to use npm library
https://github.com/topce/auto-translate-json/tree/npm

I can create PR if you want for npm branch?
Feel free to fork https://github.com/topce/auto-translate-json-library 
if you want and to publish it to your npm account and because of code ownership 

npm library still  need to stricter validation also documentation 
and package.json information need to be updated
Give it a try and let me know what you think.

**Comment by codegrue** [comment]
I think this is great and thanks for doing this. I've not had much time to code due to other obligations. I think if you can do a PR with this change I can publish it.

**Comment by codegrue** [comment]
Actually you are a contributor to this so you don't even need to do a PR, just update the code directly.

**Comment by topce** [comment]
OK I do it .
Maybe also to  move  npm library repo  to your github account , and to publish from there?  
Currently it is in https://github.com/topce/auto-translate-json-library.

**Comment by codegrue** [comment]
I'm okay if you keep the library, that way we share co-ownership

**Comment by topce** [comment]
OK 
Please do not publish new version of extensions,
still have some work to do on library to be more useful (in general extension should work),
but do not have time now ...
I tested  library in AWS translate and worked.
Also fill free to contribute to library anyway it is your idea, your code 
I just refactor little bit ;-)
