### ISSUE TITLE
Deep LFree configuration

### ISSUE THREAD

**Issue by sbellver** [codegrue/auto-translate-json#36]
Hi

I set in config Auto-translate-JSON: Deep LFree Secret Key , but when I try to run AutoTranslate said: "You must provide a Google, AWS or Azure parameters..."

But I want to use DeepL!

**Comment by topce** [comment]
Hi @sbellver 
Sorry for late reply!
Indeed message is misleading.
Did you set up your
DeepL Free Secret Key ,
DeepL Pro Secret Key ?
If not go to extension setting and set your key.

**Comment by DrJulik** [comment]
Hey @topce, running into the same error, but DeepL Free Secret Key is set up. Any ideas?

**Comment by topce** [comment]
Hello @DrJulik 
Thank you for testing 
I tested latest version and do not have this error 
So you can try to build extension 
and install it from vsix file and see if it works
or otherwise wait until @codegrue  publish new version.

@sbellver  and @DrJulik  thank you both for testing 
I do not have account for DeepL , so if you have some errors please 
open new  issue.
